language: java
jdk:
- oraclejdk7
script: ant -DBUILD_NUMBER=$BUILD_NUMBER
after_success: "./build/bintrayUpload.sh"
after_failure: grep -lEr "(</failure>)|(</error>)" ./build/artifacts/reports | xargs  cat
env:
  global:
  - BUILD_NUMBER=1.$TRAVIS_BUILD_NUMBER
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $BUILD_NUMBER" > /dev/null
  2>&1
- git push -q https://team-meerkat:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG --tags
deploy:
  provider: releases
  file_glob: true
  file:
  - "./build/artifacts/*.jar"
  - "./build/artifacts/*.pom.xml"
  skip_cleanup: true
  api_key:
    secure: NLlKCG1vJYhHPEHFeGpLBiT1DO5j7iiddKGqkY3qJ20/GMAhJzSAzwdw/aA2LKoduJDI1uLCsUXaz6LkDZvKaCi6E0FHFRzzYAlb1NI5QRDhJVjIMrhF9aW+dI4/20gofljkGY4ihNRTuNBH8+Z0fr3vFlxLvp2rlBt6o1I3o3A=
  on:
    repo: SNSOpenSource/baron-greenback
    tags: false
    all_branches: true
branches:
  except:
  - "/^[0-9].[0-9]*/"
