language: java
jdk:
- oraclejdk7
script: "ant"
env:
  global:
  - build.number=1.$TRAVIS_BUILD_NUMBER
after_success:
  - BUILD_NUMBER=1.$TRAVIS_BUILD_NUMBER
  - BINTRAY_KEY=276298114650ddba4c0fa6da8e672d6999cbef3d
  - curl -T build/artifacts/baron-greenback-$BUILD_NUMBER.jar -uspmiller:$BINTRAY_KEY https://api.bintray.com/content/sns/baron-greenback/sns/sky/sns/baron-greenback/baron-greenback/$BUILD_NUMBER/baron-greenback-$BUILD_NUMBER.jar?publish=1
