<tr>
    <td><span class="method">$item.method$</span></td>
    <td><span class="path">$item.path$</span></td>
    <td><span class="delay">$item.delay$</span></td>
    <!--<td>-->
        <!--$post(url={$base$jobs/schedule/30/crawler/crawl}, name="crawl", id=item.id)$-->
        <!--$get(name="edit", id=item.id)$-->
        <!--$get(name="export", id=item.id)$-->
        <!--$post(name="delete", id=item.id)$-->
    <!--</td>-->
</tr>