<li class="menu">
    <a href="$base$crawler/list">Crawlers</a>
</li>
<li class="menu">
    <a href="$base$crawler/status">Crawler Status</a>
</li>
<li class="menu">
    <a href="$base$crawler/failures/list">Crawler Failures</a>
</li>
<li class="menu">
    <a href="$base$crawler/executor/list">Executor Config</a>
</li>
<li class="divider"></li>
<li class="menu">
    <a href="$base$jobs/list">Jobs</a>
</li>
<li class="menu">
    <a href="$base$queues/list">Queues</a>
</li>
<li class="menu">
    <a href="$base$views/list">Views</a>
</li>
<li class="divider"></li>
<li class="menu">
    <a href="$base$batch/operations">Batch Operations</a>
</li>