$headers:
    th(class="blue " + underscores(it.name) + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="green " + underscores(it.name) + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="orange " + underscores(it.name) + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="purple " + underscores(it.name) + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name))
$
