$headers:
    th(class="blue " + it.escapedName + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="green " + it.escapedName + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="orange " + it.escapedName + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name)),
    th(class="purple " + it.escapedName + " " + sortedHeaders.(it.name), header=it.name, link=sortLinks.(it.name))
$
