

<fieldset class="fields $name$">
    <legend>$title$</legend>
    <label for="$name$recordName">Root XPath:</label><input id="$name$recordName" name="$name$recordName" value="" class="text $name$recordName" type="text"/>
    <ol>
        <li>$field(id=1, name=name)$</li>
        <li>$field(id=2, name=name)$</li>
        <li>$field(id=3, name=name)$</li>
        <li>$field(id=4, name=name)$</li>
        <li>$field(id=5, name=name)$</li>
        <li>$field(id=6, name=name)$</li>
    </ol>
</fieldset>