<label for="field$id$">XPath:</label>
<input type="text" name="$name$fields" class="text field" id="field$id$" />

<label for="alias$id$">Alias:</label>
<input type="text" name="$name$aliases" class="text alias" id="alias$id$" />

<label for="type$id$">Type:</label>
<select id="type$id$" name="$name$types">
<option value="java.lang.String" selected="selected">String</option>
<option value="java.lang.Integer">Integer</option>
<option value="java.lang.Long">Long</option>
<option value="java.util.Date">Date</option>
<option value="java.net.URI">URI</option>
<option value="java.net.URI#subfeed1">SubFeed1</option>
</select>

<label for="key$id$">Key:</label>
<input type="checkbox" name="$name$keys" class="keys" value="true" id="key$id$"/>
<input type="hidden" name="$name$keys" class="keys" value="false"/>
