

<fieldset class="fields $prefix$">
    <legend>$title$</legend>
    $input(name={$prefix$recordName}, label="Root XPath")$
    <ol>
        <li>$field(id=1, name=prefix)$</li>
        <li>$field(id=2, name=prefix)$</li>
        <li>$field(id=3, name=prefix)$</li>
        <li>$field(id=4, name=prefix)$</li>
        <li>$field(id=5, name=prefix)$</li>
        <li>$field(id=6, name=prefix)$</li>
    </ol>
</fieldset>